#%RAML 1.0 DataType


type: object
properties:
  firstName:
    description: User's Firstname
    type: string
    example: "Jins"

  lastName: 
    description: User's Lastname  
    type: string
    example: "Wilson"  

  emailID:
    description: User's email address
    type: string
    example: "testokta123@gmail.com"  

  mobileNo: 
    description: Phone Number entered by user
    type: string
    example: "8887666542"  

  username:
    description: EmailId entered by user
    type: string
    example: "testokta123@gmail.com"

  password: 
    description: Password entered by the user during registration
    type: string
    example: "test@123"
    
  