#%RAML 1.0 DataType

type: object
properties:  
  oldPassword:
      description: User's Current password
      type: string
      example: "testokta123"

  newPassword: 
    description: New Password entered by the user 
    type: string
    example: "test@123"