#%RAML 1.0 NamedExample

value:
  id: "00ub0oNGTSWTBKOLGLNR"
  status: "STAGED"
  created: 2013-07-02T21:36:25.344Z
  activated: null
  statusChanged: null
  lastLogin: null
  lastUpdated: 2013-07-02T21:36:25.344Z
  passwordChanged: 2013-07-02T21:36:25.344Z
  profile:
    firstName: "Isaac"
    lastName: "Brock"
    email: "isaac.brock@gmail.com"
    login: "isaac.brock@gmail.com"
    mobilePhone: "555-415-1337"
  
  credentials: 
    password: "testOkta"
    recovery_question: 
      question: "Who's a major player in the cowboy scene?"