#%RAML 1.0 NamedExample

value:
-
  customerID: "CUST101"
  firstname: "James"
  lastname: "Marun"
  emailID: "james123@gmail.com"
  mobileNo: "555467588"
  status: "active"
  creationDate: 2020-07-21T04:34:41.098Z
  updationDate: 2020-07-22T05:10:30.067Z
-
  customerID: "CUST102"
  firstname: "Wilson"
  lastname: "Gavin"
  emailID: "willsmail@gmail.com"
  mobileNo: "767564348"
  status: "inactive"
  creationDate: 2020-06-20T08:34:41.012Z
  updationDate: 2020-07-22T05:12:30.097Z
-
  customerID: "CUST103"
  firstname: "Rosie"
  lastname: "Philip"
  emailID: "rosiephilip@gmail.com"
  mobileNo: "12554313"
  status: "active"
  creationDate: 2020-05-11T04:34:41.098Z
  updationDate: 2020-07-19T05:10:30.067Z