#%RAML 1.0 NamedExample

value:
-
  customerID: "CUST101"
  firstname: "James"
  lastname: "Marun"
  emailID: "james123@gmail.com"
  mobileNo: "555467588"
  status: "active"
  creationDate: 2020-07-21T04:34:41.098Z
  updationDate: 2020-07-22T05:10:30.067Z