#%RAML 1.0 NamedExample

value:
-
  subscriptionID: 1001
  customerID: "CUST101"
  orgin: "ABW"
  destination: "VIC"
  fromTime: 0
  toTime: 60
  status: "active"
  notificationTime: 30
  creationDate: 2020-07-21T04:34:41.098Z
  updationDate: 2020-07-22T05:10:30.067Z
-
  
  subscriptionID: 1002
  customerID: "CUST101"
  orgin: "WAT"
  destination: "BMH"
  fromTime: 0
  toTime: 60
  status: "active"
  notificationTime: 30
  creationDate: 2020-07-21T04:34:41.098Z
  updationDate: 2020-07-22T05:10:30.067Z
