#%RAML 1.0 DataType

type: object
properties:
  firstName: 
    description: Customer's Firstname
    type: string
    example: "Jins"

  lastName: 
    description: Customer's Lastname
    type: string
    example: "Wilson"

  emailID: 
    description: Customer's emailid entered at the time of registration
    type: string
    example: "wilsonjins@gmail.com"

  mobileNo: 
    description: Mobile number entered by customer at registration time
    type: string
    example: "8888566497"

  password:
    description: Password entered by user
    type: string
    example: "test@123"  