#%RAML 1.0 DataType

type: object
properties:  
  username:
      description: EmailId entered by user
      type: string
      example: "testokta123@gmail.com"

  password: 
    description: Password entered by the user during registration
    type: string
    example: "test@123"

  newpassword?:
    description: New Password entered by user 
    type: string
    example: "test@123"   